# Generated by Django 4.2.7 on 2023-11-03 18:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customers",
            options={"verbose_name_plural": "Customers"},
        ),
    ]
