# Generated by Django 4.2.7 on 2023-11-03 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0002_alter_customers_options"),
        ("purchase", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchase",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchases",
                to="customer.customers",
            ),
        ),
    ]
